# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # try to perform a nodejs setup
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # try to install node-unifi using npm
    - name: install node-unifi
      run: npm install

    # install required dependencies
    - name: install dependencies
      run: |
        sudo apt -qq update || true
        sudo apt install ca-certificates apt-transport-https

    # install UniFi controller
    - name: install UniFi controller using EUS
      run: |
        export TERM=vt100
        sudo $GITHUB_WORKSPACE/.github/workflows/unifi-install.sh --skip --server-ip 127.0.0.1

    # run npm tests
    - name: run npm tests
      run: npm test

    - name: remote debug tmate session
      uses: mxschmitt/action-tmate@v1
